name: Build binaries

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-ta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          path: optee-uc-fde
          persist-credentials: false
      - name: Checkout OP-TEE OS
        uses: actions/checkout@v7
        with:
          repository: op-tee/optee_os
          path: optee
          ref: 753afbbee1682f5d16fd30e87b31058a4fd4f4b8 # 4.10.0
          persist-credentials: false
      - name: Install build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf device-tree-compiler python3-pyelftools
      - name: Build OP-TEE
        env:
          PLATFORM: vexpress-qemu_armv8a
          CFG_EARLY_TA: y
          CFG_IN_TREE_EARLY_TAS: fde_key_handler/fd1b2a86-3668-11eb-adc1-0242ac120002
        run: |
          ln -svr optee-uc-fde/ta/fde_key_handler optee/ta/
          make -C optee -j"$(nproc)"
          test -f optee/out/arm-plat-vexpress/ta/fde_key_handler/fd1b2a86-3668-11eb-adc1-0242ac120002.elf
